name: linger
description: Islam Learning Application\

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  animated_splash_screen:
  sms_autofill: ^2.2.0
  toast: ^0.3.0
  email_validator: ^2.0.1
  flappy_search_bar: ^1.7.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  google_sign_in: ^5.4.0

  cupertino_icons: ^1.0.2
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  http: ^0.13.4
  expandable: ^5.0.1
  rive: ^0.9.0
  dio: ^4.0.0
  path_provider: ^2.0.9
  provider: ^6.0.3
  flutter_svg: ^1.1.1+1
  cached_network_image: ^3.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  json_store: ^2.0.0-nullsafety.0
  logger: ^1.1.0
  get_it: ^7.2.0
  auto_route: ^4.2.1
  image_picker: ^0.8.5+3
  loader_overlay: ^2.0.7
  flutter_swiper_null_safety: ^1.0.2
  responsive_sizer: ^3.1.0
  confetti: ^0.7.0
  lottie: ^1.4.2

  dots_indicator: ^2.1.0
  flutter_facebook_auth: ^4.4.0+1
  flutter_rating_bar:
  sizer: ^2.0.15
  intl_phone_number_input: ^0.7.0+2
  country_state_city_picker: ^1.2.8
  chewie: ^1.3.5
  video_player: ^2.4.7
  auto_orientation: ^2.2.1
  flutter_advanced_calendar: ^1.2.0
  loading_animation_widget:
  assets_audio_player:
  flutter_neumorphic: ^3.2.0
  share_plus: ^4.4.0
  http_parser: ^4.0.1
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.5
  flutter_webview_pro: ^3.0.1+4
  carousel_slider: ^4.1.1
  razorpay_web: ^1.3.5

  stacked_services: ^0.8.6
  stacked: ^2.1.7
  sqflite: ^2.2.2
  get: ^4.6.5
  get_storage: ^2.0.3
  file_picker: ^5.2.4
  dotted_border: ^2.0.0+3
  flutter_countdown_timer: ^4.1.0


dependency_overrides:
  image_picker_android: 0.8.4+13

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  build_runner:
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/

  fonts:
    - family: Reguler
      fonts:
        - asset: assets/fonts/sf-pro/SF-Pro-Display-Regular.otf
    - family: Medium
      fonts:
        - asset: assets/fonts/sf-pro/SF-Pro-Display-Medium.otf
    - family: Bold
      fonts:
        - asset: assets/fonts/sf-pro/SF-Pro-Display-Bold.otf
    - family: Italic
      fonts:
        - asset: assets/fonts/sf-pro/SF-Pro-Display-BlackItalic.otf
    - family: Light
      fonts:
        - asset: assets/fonts/sf-pro/SF-Pro-Display-Light.otf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/sf-pro/SF-Pro-Display-SemiBold.otf
    - family: AlumniRegular
      fonts:
        - asset: assets/fonts/alumnisansinline/AlumniSansInlineOne-Regular.ttf

